// Shared brand catalogue: slug, logo domain, and the per-brand SEO content used to
// generate each brand's individual repair page. Keeping this in one place means the
// /brands grid, the "Brands" nav dropdown and the 38 brand pages all stay in sync.

export interface BrandEntry {
  name: string;
  slug: string; // route is /{slug}
  domain: string; // used for the token-free favicon logo
  tech: string; // headline technology / positioning line
  tier: 'Premium European' | 'Global Major' | 'Asian' | 'Regional / Value';
  intro: string; // 2–3 sentence unique hero/intro paragraph
  models: string; // representative model ranges sold in the UAE
  faults: { title: string; desc: string }[]; // 5 unique common faults
  whyLine: string; // one-line "why us for this brand" differentiator
  repairsCount: string; // social-proof stat for the hero
  metaTitle: string; // <= 65 chars
  metaDesc: string; // <= 150 chars
}

const s = (name: string) =>
  name
    .toLowerCase()
    .replace(/\+/g, ' plus ')
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');

function make(
  name: string,
  domain: string,
  tier: BrandEntry['tier'],
  tech: string,
  intro: string,
  models: string,
  faults: { title: string; desc: string }[],
  whyLine: string,
  repairsCount: string,
  metaTitle: string,
  metaDesc: string,
): BrandEntry {
  return {
    name,
    slug: `${s(name)}-washing-machine-repair`,
    domain,
    tech,
    tier,
    intro,
    models,
    faults,
    whyLine,
    repairsCount,
    metaTitle,
    metaDesc,
  };
}

export const BRANDS: BrandEntry[] = [
  make(
    'LG', 'lg.com', 'Global Major',
    'Direct Drive · AI DD · TurboWash',
    "LG washing machines run belt-free Direct Drive motors and AI DD fabric detection, making them quiet and efficient — until a sensor, drive board or door lock plays up. Our LG-trained technicians repair the full range across Dubai, from front-load WM machines to top-load TurboDrum models, with genuine parts on the van.",
    'WM/WD front-load series, TurboDrum & T-series top-load, AI DD inverter models',
    [
      { title: 'LE / CL Locked-Motor Error', desc: "The drum won't turn and the board reports a locked motor — usually the Hall sensor or a loose rotor bolt, not the motor itself. Repair: AED 200–450." },
      { title: 'Door Lock Failure (FE / FH)', desc: "The door won't open after a cycle or locks mid-wash, common in machines 3–6 years old. Repair: AED 200–350." },
      { title: 'Slow or No Drainage', desc: 'Inverter-driven pumps clog or fail, leaving water in the drum with UE/OE codes. Repair: AED 250–450.' },
      { title: 'Drum Bearing Wear', desc: 'Grinding on spin and poor extraction on 6–8 year-old Direct Drive machines. Repair: AED 400–700.' },
      { title: 'Control Board Malfunction', desc: 'The machine stops responding to buttons or halts mid-cycle. Repair: AED 350–600.' },
    ],
    '15+ years of specialised LG repair experience with same-day genuine parts for the top LG models in the UAE.',
    '1,200+',
    'LG Washing Machine Repair Dubai | Same-Day Genuine Parts',
    'Same-day LG washing machine repair in Dubai. Certified techs fix LE/door-lock/drainage faults with genuine parts & 12-month warranty.',
  ),
  make(
    'Samsung', 'samsung.com', 'Global Major',
    'EcoBubble · Digital Inverter · VRT',
    "Samsung's EcoBubble and Digital Inverter machines are everywhere in Dubai, but their inverter motors and control boards feel the strain of extreme summer heat. We carry genuine WF, WD and AI-series components in stock and diagnose the whole EcoBubble system, so your Samsung washes properly again the same day.",
    'WF front-load, WA/WD top-load, EcoBubble & AI EcoBubble series',
    [
      { title: '3E / 3E1 Motor Errors', desc: 'A Hall-sensor or motor-connector fault rather than a dead motor — we test before we replace. Repair: AED 200–450.' },
      { title: 'Inverter Motor Failure in Heat', desc: "Strange noises, no spin or unexpected stops as Dubai's heat stresses the inverter. Repair: AED 450–750." },
      { title: 'Water Inlet Valve Fault', desc: "The machine won't fill or fills slowly from a stuck or corroded valve. Repair: AED 150–300." },
      { title: 'Bearing Noise (WF/WD)', desc: 'Grinding and vibration during spin on 4–7 year-old machines. Repair: AED 380–650.' },
      { title: 'Control Panel Board Fault', desc: "Error codes, an unresponsive panel or programs that won't start. Repair: AED 300–500." },
    ],
    'Genuine Samsung components in stock and deep experience with EcoBubble sensor and inverter systems used across Dubai.',
    '1,100+',
    'Samsung Washing Machine Repair Dubai | EcoBubble Experts',
    'Same-day Samsung washing machine repair in Dubai. EcoBubble & Digital Inverter specialists, genuine parts, 12-month warranty.',
  ),
  make(
    'Bosch', 'bosch-home.com', 'Premium European',
    'EcoSilence Drive · VarioPerfect · i-Dos',
    "Bosch machines are built for precision with EcoSilence Drive motors and EcoTherm heating, which makes them especially sensitive to Dubai's hard water. Our Bosch-certified team specialises in limescale-related faults and offers dedicated descaling maintenance to keep the heating system and pump healthy.",
    'Serie 2/4/6/8 front-load, WAJ/WAT/WGG series, i-Dos models',
    [
      { title: 'Heating Element Limescale', desc: "Poor wash performance and rising energy use as Dubai's hard water scales the heater. Repair: AED 150–300 (preventive AED 80–120)." },
      { title: 'F21 Motor Fault', desc: "The drum won't turn or turns erratically — often the carbon-free motor's control module or wiring. Repair: AED 350–700." },
      { title: 'Door Seal Degradation', desc: "Leaks, mould and odours as heat accelerates rubber wear on 3–5 year-old machines. Repair: AED 180–350." },
      { title: 'Water Temperature Sensor Fault', desc: 'Incorrect wash temperature, error codes and wasted energy. Repair: AED 120–250.' },
      { title: 'Pump Impeller Breakage', desc: 'Drain issues and noise during drainage. Repair: AED 200–380.' },
    ],
    'Bosch-certified technicians with dedicated hard-water maintenance packages and full access to the Bosch parts catalogue.',
    '900+',
    'Bosch Washing Machine Repair Dubai | Hard-Water Experts',
    'Same-day Bosch washing machine repair in Dubai. Limescale & EcoSilence specialists, genuine parts, 12-month warranty.',
  ),
  make(
    'Siemens', 'siemens-home.bsh-group.com', 'Premium European',
    'iQdrive · iSensoric · varioSpeed',
    "Siemens shares the BSH platform with Bosch but adds iSensoric load-and-soil sensing and the brushless iQdrive motor. These premium electronics reward precise, brand-specific diagnosis — exactly what our Dubai technicians provide, with genuine Siemens parts sourced for the UAE market.",
    'iQ300/500/700 front-load, varioSpeed & iSensoric models',
    [
      { title: 'iQdrive Bearing Wear', desc: 'Grinding or rattling on spin in machines 5+ years old. Repair: AED 400–700.' },
      { title: 'iSensoric Sensor Fault', desc: 'Incorrect water dosing or cycle times from a drifting load/soil sensor. Repair: AED 200–380.' },
      { title: 'Door Seal Mould & Leaks', desc: "Common in Dubai's humidity and heat, causing leaks and odours. Repair: AED 180–350." },
      { title: 'Drain Pump & Filter Blockage', desc: 'Slow or failed drainage from debris in the pump filter. Repair: AED 180–350.' },
      { title: 'Electronic Control Freeze', desc: "The machine freezes or won't start a cycle. Repair: AED 300–550." },
    ],
    'Specialised experience with Siemens premium sensor-driven systems and genuine parts sourcing for the UAE market.',
    '700+',
    'Siemens Washing Machine Repair Dubai | iQdrive Experts',
    'Same-day Siemens washing machine repair in Dubai. iQdrive & iSensoric specialists, genuine parts, 12-month warranty.',
  ),
  make(
    'Whirlpool', 'whirlpool.com', 'Global Major',
    '6th Sense · Adaptive Wash · Zen',
    "Whirlpool's 6th Sense technology adapts water and energy to each load, and its top-load models are a common sight in Dubai villas and apartments. We keep genuine Whirlpool parts in stock and have a decade of experience repairing both its front-load and top-load ranges.",
    'FreshCare front-load, Stainwash & 360 top-load, 6th Sense series',
    [
      { title: 'Drain Pump Failure', desc: "Water won't drain and clothes stay wet — the most common fault on older top-load models. Repair: AED 250–450." },
      { title: 'Hose & Connector Cracking', desc: 'Cracks from pressure and temperature cycling lead to leaks. Repair: AED 100–250.' },
      { title: 'Control Panel Responsiveness', desc: "Buttons stick or don't respond and cycles pause unexpectedly. Repair: AED 200–350." },
      { title: 'Bearing & Drum Problems', desc: 'Grinding, vibration and drum movement on 5+ year-old machines. Repair: AED 350–600.' },
      { title: 'Water Level Sensor Fault', desc: 'Over- or under-filling that affects wash quality. Repair: AED 150–280.' },
    ],
    '10+ years of Whirlpool repair history in Dubai with a preventive programme that cuts future repairs by up to 60%.',
    '850+',
    'Whirlpool Washing Machine Repair Dubai | 6th Sense Experts',
    'Same-day Whirlpool washing machine repair in Dubai. Front & top-load specialists, genuine parts, 12-month warranty.',
  ),
  make(
    'Hisense', 'hisense.com', 'Asian',
    'Purejet · Inverter · Auto Dosing',
    "Hisense has become one of the fastest-growing washing machine brands in Dubai, offering inverter motors and Purejet washing at a sharp price. We repair the full Hisense line-up, keep common inverter and pump parts in stock, and back every fix with a genuine-parts guarantee.",
    'WFQA/WFQP front-load, top-load & Purejet inverter models',
    [
      { title: 'Inverter Motor / Board Fault', desc: 'No spin, mid-cycle stops or error codes from the inverter drive. Repair: AED 300–650.' },
      { title: 'Drain Pump Blockage', desc: 'Water remains in the drum with a drainage error. Repair: AED 200–400.' },
      { title: 'Door Lock Fault', desc: "The door won't lock or release, halting the cycle. Repair: AED 180–350." },
      { title: 'Water Inlet Valve Fault', desc: 'Slow filling or no fill from a stuck valve. Repair: AED 150–300.' },
      { title: 'Bearing & Vibration', desc: 'Noise and shaking on spin as bearings wear. Repair: AED 350–600.' },
    ],
    'Growing Hisense expertise in Dubai with in-stock inverter and pump parts for fast, affordable repairs.',
    '600+',
    'Hisense Washing Machine Repair Dubai | Inverter Experts',
    'Same-day Hisense washing machine repair in Dubai. Inverter & Purejet specialists, genuine parts, 12-month warranty.',
  ),
  make(
    'Panasonic', 'panasonic.com', 'Asian',
    'Econavi · StainMaster · Aqua Beat',
    "Panasonic machines pair Econavi sensors with stainless-steel tubs and Aqua Beat washing for gentle, efficient cleaning. Our Dubai technicians know its sensor systems inside out and keep a complete spare-parts catalogue for every Panasonic model sold in the UAE.",
    'NA-series front-load, top-load & Econavi StainMaster models',
    [
      { title: 'Water Level Sensor Fault', desc: 'Over- or under-filling that hurts wash quality and efficiency, common on NA-series. Repair: AED 120–250.' },
      { title: 'Econavi Sensor / Eco-Mode Fault', desc: "Eco programs that don't activate or work correctly. Repair: AED 150–300." },
      { title: 'Door Mechanism Problem', desc: "The door won't lock or the cycle starts before it closes. Repair: AED 180–350." },
      { title: 'Motor Speed-Control Fault', desc: 'Incorrect spin speeds and inconsistent performance. Repair: AED 200–400.' },
      { title: 'Drum Surface Damage', desc: 'Rust spots in hard-water areas that affect wash quality. Repair: AED 250–450.' },
    ],
    'Complete Panasonic spare-parts catalogue and Econavi sensor expertise for Dubai homes.',
    '650+',
    'Panasonic Washing Machine Repair Dubai | Econavi Experts',
    'Same-day Panasonic washing machine repair in Dubai. Econavi & Aqua Beat specialists, genuine parts, 12-month warranty.',
  ),
  make(
    'Haier', 'haier.com', 'Asian',
    'Direct Motion · Magic Filter · Fuzzy Logic',
    "Haier washing machines are increasingly common in new Dubai apartments, built around Direct Motion motors and the Magic Filter lint system. We have specialised knowledge of Haier's inverter and Fuzzy Logic sensing and source genuine parts for both front-load and top-load ranges.",
    'HW front-load, top-load & Direct Motion inverter models',
    [
      { title: 'Magic Filter Clogging', desc: 'Reduced wash and drainage performance from lint build-up. Repair: AED 100–200.' },
      { title: 'Direct Motion Motor Fault', desc: 'Inconsistent agitation or spin speed. Repair: AED 350–600.' },
      { title: 'Lid Lock / Sensor Error', desc: 'The machine pauses repeatedly during a cycle. Repair: AED 180–320.' },
      { title: 'Fuzzy Logic Miscalibration', desc: 'Incorrect water levels for the load size. Repair: AED 150–300.' },
      { title: 'Drain Pump Fault', desc: 'Water backs up with a drainage error. Repair: AED 200–400.' },
    ],
    'Specialised Haier Direct Motion and Magic Filter knowledge for the machines going into new Dubai homes.',
    '550+',
    'Haier Washing Machine Repair Dubai | Direct Motion Experts',
    'Same-day Haier washing machine repair in Dubai. Direct Motion & Magic Filter specialists, genuine parts, 12-month warranty.',
  ),
  make(
    'Beko', 'beko.com', 'Global Major',
    'AquaTech · ProSmart Inverter · SteamCure',
    "Beko is one of the best-selling washing machine brands in the UAE, known for AquaTech drums and ProSmart Inverter motors that balance performance with value. Our technicians repair the full Beko range and keep genuine inverter, pump and seal parts in stock for same-day fixes.",
    'WTV/WMY front-load, AquaTech & ProSmart Inverter models',
    [
      { title: 'ProSmart Inverter Fault', desc: 'No spin, mid-cycle cut-outs or motor error codes. Repair: AED 300–650.' },
      { title: 'Drain Pump Blockage', desc: 'Standing water and a drainage error code. Repair: AED 200–400.' },
      { title: 'Door Seal Leak', desc: "Water at the front of the machine as the gasket wears in Dubai's heat. Repair: AED 180–350." },
      { title: 'Heating Element Limescale', desc: 'Longer cycles and cool washes from hard-water scaling. Repair: AED 150–300.' },
      { title: 'Bearing Wear', desc: 'Grinding and vibration on spin. Repair: AED 350–600.' },
    ],
    'One of the most-serviced value brands in Dubai, with genuine Beko parts always in stock.',
    '800+',
    'Beko Washing Machine Repair Dubai | ProSmart Inverter Fix',
    'Same-day Beko washing machine repair in Dubai. AquaTech & ProSmart Inverter specialists, genuine parts, 12-month warranty.',
  ),
  make(
    'Hoover', 'hoover.com', 'Premium European',
    'AXI · Wizard Wi-Fi · Motion Sense',
    "Hoover washing machines bring smart AXI and Wi-Fi Wizard connectivity to Dubai homes, alongside dependable mechanical designs. We repair both the connected and conventional Hoover ranges, resolving app, motor and drainage faults with genuine spare parts.",
    'AXI front-load, Wizard Wi-Fi & H-Wash series',
    [
      { title: 'Motor / Belt Fault', desc: 'No spin or a slipping belt leaving clothes soaked. Repair: AED 300–650.' },
      { title: 'Wi-Fi / Control Board Fault', desc: "Connectivity drops or the panel won't respond. Repair: AED 250–500." },
      { title: 'Drain Pump Blockage', desc: 'Water remains in the drum after the cycle. Repair: AED 200–400.' },
      { title: 'Door Lock Fault', desc: "The door won't open or lock, stopping the wash. Repair: AED 180–350." },
      { title: 'Bearing & Drum Wear', desc: 'Grinding and vibration on older machines. Repair: AED 350–600.' },
    ],
    'Experience with both smart Wi-Fi and conventional Hoover machines, with genuine parts for the UAE range.',
    '400+',
    'Hoover Washing Machine Repair Dubai | AXI & Wizard Fix',
    'Same-day Hoover washing machine repair in Dubai. Smart AXI & Wizard Wi-Fi specialists, genuine parts, 12-month warranty.',
  ),
  make(
    'Super General', 'sgcgroup.com', 'Regional / Value',
    'Twin-Tub · Auto & Semi-Auto Ranges',
    "Super General is a UAE household name, popular for affordable automatic, semi-automatic and twin-tub washing machines. We repair the full Super General line-up across Dubai villas, apartments and staff accommodation, keeping belts, motors, timers and pumps in stock for fast, budget-friendly fixes.",
    'Automatic front-load, semi-automatic & twin-tub models',
    [
      { title: 'Pulsator / Belt Fault', desc: 'Weak or no wash action on semi-auto and twin-tub models. Repair: AED 140–320.' },
      { title: 'Spin Motor / Bearing Fault', desc: 'The spinner stalls or grinds, leaving clothes soaked. Repair: AED 180–380.' },
      { title: 'Drain Valve / Pump Fault', desc: "Water won't drain from the tub. Repair: AED 120–300." },
      { title: 'Timer / Control Fault', desc: "The cycle won't advance or the buzzer stays silent. Repair: AED 130–300." },
      { title: 'Water Leak from Tub', desc: 'Leaks from a worn seal or cracked valve. Repair: AED 100–280.' },
    ],
    'A go-to for Super General repairs in Dubai, with affordable parts and fast turnaround for high-usage homes.',
    '900+',
    'Super General Washing Machine Repair Dubai | Same-Day Fix',
    'Same-day Super General washing machine repair in Dubai. Auto, semi-auto & twin-tub experts, genuine parts, warranty.',
  ),
  make(
    'Daewoo', 'daewooelectronics.co.uk', 'Regional / Value',
    'Compact Auto · Twin-Tub · Bubble Wash',
    "Daewoo washing machines are valued in Dubai for compact, affordable designs that suit apartments and staff accommodation. Our technicians have long-standing familiarity with Daewoo's automatic and twin-tub mechanics and keep capacitors, belts, timers and drain valves in stock.",
    'Compact automatic, twin-tub & Bubble Wash models',
    [
      { title: 'Wash Motor Capacitor Fault', desc: "The motor hums but won't start agitation. Repair: AED 140–280." },
      { title: 'Drain Valve Cracking', desc: "Leaks or failure to drain from heat-aged valves in Dubai's climate. Repair: AED 100–240." },
      { title: 'Timer Mechanism Sticking', desc: "The cycle pauses or won't complete on the dial. Repair: AED 130–280." },
      { title: 'Pulsator Coupling Wear', desc: 'Weak or inconsistent wash action. Repair: AED 130–280.' },
      { title: 'Power Switch / Cord Fault', desc: 'Intermittent power loss during operation. Repair: AED 100–220.' },
    ],
    'Long-standing familiarity with Daewoo compact and twin-tub units common in smaller Dubai homes.',
    '500+',
    'Daewoo Washing Machine Repair Dubai | Compact & Twin-Tub',
    'Same-day Daewoo washing machine repair in Dubai. Compact auto & twin-tub experts, genuine parts, 12-month warranty.',
  ),
  make(
    'Toshiba', 'toshiba.com', 'Asian',
    'Great Waves · T-Wash · Real Inverter',
    "Toshiba washing machines are prized for durable Japanese engineering, Great Waves drums and Real Inverter motors. We repair Toshiba's automatic, semi-automatic and inverter machines across Dubai, sourcing genuine parts for both current and older, discontinued models.",
    'Great Waves front-load, semi-automatic & Real Inverter models',
    [
      { title: 'Real Inverter Motor Fault', desc: 'No spin or mid-cycle stops from the inverter drive. Repair: AED 350–650.' },
      { title: 'Agitator / Belt Wear', desc: "The wash side runs but clothes don't move on semi-auto models. Repair: AED 140–300." },
      { title: 'Drain Valve / Pump Fault', desc: 'Slow or failed drainage. Repair: AED 120–350.' },
      { title: 'Motor Bearing Noise', desc: 'Grinding during agitation on 4+ year-old machines. Repair: AED 180–350.' },
      { title: 'Timer / Control Fault', desc: "The cycle won't progress or the buzzer is silent. Repair: AED 130–300." },
    ],
    'Extensive experience with Toshiba automatic and semi-automatic lines, among the most widely sold in the UAE.',
    '600+',
    'Toshiba Washing Machine Repair Dubai | Real Inverter Fix',
    'Same-day Toshiba washing machine repair in Dubai. Great Waves & Real Inverter experts, genuine parts, warranty.',
  ),
  make(
    'Hitachi', 'hitachi.com', 'Asian',
    'Push & Wash · Beat Wave · Auto Dosing',
    "Hitachi washing machines are known for durable Japanese engineering and gentle Beat Wave washing, and they are widely used across Dubai homes. We diagnose both the mechanical and electronic Hitachi systems and source genuine parts for older and current models alike.",
    'Beat Wave front-load, top-load & Push & Wash models',
    [
      { title: 'Motor & Belt Wear', desc: 'No spin or a slipping belt leaving clothes soaked. Repair: AED 300–650.' },
      { title: 'Water Level Sensor Fault', desc: 'Over- or under-filling affecting wash quality. Repair: AED 150–280.' },
      { title: 'Drainage Blockage', desc: 'Water remains in the drum from a blocked pump or hose. Repair: AED 200–400.' },
      { title: 'Control Board Fault', desc: 'The machine freezes or halts mid-cycle on higher-end models. Repair: AED 300–550.' },
      { title: 'Bearing & Drum Wear', desc: 'Grinding and vibration on spin. Repair: AED 350–600.' },
    ],
    'Trusted for Hitachi repairs in Dubai, with genuine parts for both current and older models.',
    '550+',
    'Hitachi Washing Machine Repair Dubai | Beat Wave Experts',
    'Same-day Hitachi washing machine repair in Dubai. Beat Wave & Push & Wash experts, genuine parts, 12-month warranty.',
  ),
  make(
    'Midea', 'midea.com', 'Asian',
    'i-Clean · Knight Inverter · Auto Dosing',
    "Midea is a fast-growing value brand in Dubai, offering inverter motors, i-Clean drums and high-capacity tubs at an accessible price. We repair Midea's automatic and twin-tub ranges and keep genuine inverter, pump and belt parts on hand for same-day service.",
    'MF front-load, top-load, twin-tub & Knight Inverter models',
    [
      { title: 'Knight Inverter Fault', desc: 'No spin or mid-cycle cut-outs from the inverter drive. Repair: AED 300–650.' },
      { title: 'Spin Imbalance / Vibration', desc: 'The machine shakes or "walks" during spin. Repair: AED 200–380.' },
      { title: 'Pulsator Gear Wear', desc: 'Reduced wash action with clothes not agitating fully. Repair: AED 180–350.' },
      { title: 'Drain Outlet Blockage', desc: 'Slow or no drainage from the tub. Repair: AED 100–220.' },
      { title: 'Motor Overheating', desc: "The machine stops mid-cycle and won't restart immediately. Repair: AED 180–350." },
    ],
    'Strong Midea parts availability for the high-capacity machines popular in larger Dubai homes.',
    '600+',
    'Midea Washing Machine Repair Dubai | Knight Inverter Fix',
    'Same-day Midea washing machine repair in Dubai. i-Clean & Knight Inverter experts, genuine parts, 12-month warranty.',
  ),
  make(
    'Ariston', 'ariston.com', 'Premium European',
    'Aqua Care · Direct Injection · Active Care',
    "Ariston brings Italian design and Aqua Care technology to Dubai laundry rooms, with efficient Direct Injection washing. We repair the full Ariston front-load range, resolving heating, drainage and electronic faults with genuine European parts.",
    'Aqua Care & Active Care front-load series',
    [
      { title: 'Heating Element Limescale', desc: "Cool washes and rising energy use from Dubai's hard water. Repair: AED 150–300." },
      { title: 'Drain Pump Fault', desc: 'Standing water and a drainage error code. Repair: AED 200–400.' },
      { title: 'Door Lock / Seal Fault', desc: "The door won't lock, or the gasket leaks. Repair: AED 180–350." },
      { title: 'Control Board Fault', desc: "Error codes or a cycle that won't start. Repair: AED 300–550." },
      { title: 'Bearing Wear', desc: 'Grinding and vibration on spin. Repair: AED 350–600.' },
    ],
    'Genuine European parts and Ariston Aqua Care expertise for Dubai homes.',
    '350+',
    'Ariston Washing Machine Repair Dubai | Aqua Care Experts',
    'Same-day Ariston washing machine repair in Dubai. Aqua Care & Direct Injection experts, genuine parts, warranty.',
  ),
  make(
    'Miele', 'miele.com', 'Premium European',
    'Honeycomb Drum · ProfiEco Motor · TwinDos',
    "Miele is the premium end of the market, engineered to last decades with its honeycomb drum, ProfiEco motor and TwinDos dosing. When one does need attention it demands genuine Miele parts and careful, brand-trained handling — exactly how our Dubai specialists approach every Miele repair.",
    'W1 front-load, TwinDos & honeycomb-drum series',
    [
      { title: 'Water Inlet / Drain Valve Fault', desc: 'Filling or drainage problems from a failed valve. Repair: AED 200–400.' },
      { title: 'Electronic Control Error', desc: 'Program faults or an unresponsive display. Repair: AED 300–600.' },
      { title: 'Door Lock Fault', desc: "The door won't open or lock at cycle end. Repair: AED 200–380." },
      { title: 'Heater Scaling', desc: "Reduced heating performance from Dubai's hard water. Repair: AED 200–380." },
      { title: 'TwinDos / Dosing Fault', desc: 'Incorrect or no detergent dispensing. Repair: AED 200–400.' },
    ],
    'Careful, brand-trained Miele handling with genuine parts to protect a premium, long-life machine.',
    '300+',
    'Miele Washing Machine Repair Dubai | Genuine Parts Only',
    'Same-day Miele washing machine repair in Dubai. Honeycomb-drum & TwinDos specialists, genuine parts, warranty.',
  ),
  make(
    'Nikai', 'nikai.com', 'Regional / Value',
    'Single & Twin-Tub · Semi-Automatic',
    "Nikai is one of the most widely sold budget washing machine brands in the UAE, popular in apartments and labour accommodation. We have extensive experience with Nikai's single-tub, twin-tub and semi-automatic mechanics and keep affordable belts, motors and drain valves in stock.",
    'Single-tub, twin-tub & semi-automatic models',
    [
      { title: 'Drive Belt Slipping / Snapping', desc: 'The pulsator runs weakly or not at all. Repair: AED 140–300.' },
      { title: 'Drain Plug / Valve Leak', desc: 'Water seeping from the base of the tub. Repair: AED 100–230.' },
      { title: 'Motor Overheating', desc: "The machine stops mid-cycle and won't restart immediately. Repair: AED 150–300." },
      { title: 'Timer Buzzer Silent', desc: 'The cycle completes silently, easy to miss. Repair: AED 120–250.' },
      { title: 'Worn Motor Mounts', desc: 'Excess noise and vibration during agitation. Repair: AED 120–280.' },
    ],
    'Extensive Nikai experience for budget-conscious homes and labour accommodation across Dubai.',
    '700+',
    'Nikai Washing Machine Repair Dubai | Twin-Tub Experts',
    'Same-day Nikai washing machine repair in Dubai. Twin-tub & semi-automatic experts, genuine parts, 12-month warranty.',
  ),
  make(
    'Electrolux', 'electrolux.com', 'Premium European',
    'PerfectCare · SteamCare · UltraMix',
    "Electrolux machines pair PerfectCare drums with SteamCare programs and UltraMix pre-mixing for gentle, thorough washing. Our technicians understand its sensor systems and stock genuine Electrolux components for the full UAE line-up, restoring both steam and standard cycles properly.",
    'PerfectCare 600/700/800, SteamCare & UltraMix series',
    [
      { title: 'Water-Level Sensor Fault', desc: 'Over- or under-filling affecting wash quality and efficiency. Repair: AED 120–280.' },
      { title: 'Door Mechanism Fault', desc: "The door won't lock or the cycle starts before it closes. Repair: AED 180–350." },
      { title: 'Motor Speed-Control Fault', desc: 'Incorrect spin speeds and inconsistent performance. Repair: AED 200–400.' },
      { title: 'Drainage Fault', desc: 'Slow or failed drainage. Repair: AED 180–380.' },
      { title: 'SteamCare / Heating Fault', desc: 'Weak steam output or cool washes from scaling. Repair: AED 200–400.' },
    ],
    'Electrolux sensor and SteamCare expertise with genuine parts for the full UAE range.',
    '450+',
    'Electrolux Washing Machine Repair Dubai | PerfectCare Fix',
    'Same-day Electrolux washing machine repair in Dubai. PerfectCare & SteamCare experts, genuine parts, warranty.',
  ),
  make(
    'AEG', 'aeg.com', 'Premium European',
    'ÖKOMix · ProSense · 6000/7000/8000',
    "AEG delivers German engineering with ÖKOMix detergent pre-mixing and ProSense load sensing. Our Dubai technicians handle AEG's premium electronics and drum systems, sourcing genuine components to keep these long-life machines running.",
    '6000/7000/8000 series, ÖKOMix & ProSense models',
    [
      { title: 'ProSense Sensor Fault', desc: 'Wrong cycle times or water dosing from a drifting sensor. Repair: AED 200–400.' },
      { title: 'Heating Element Scaling', desc: "Cool washes and higher energy use from Dubai's hard water. Repair: AED 150–320." },
      { title: 'Door Lock / Seal Fault', desc: "The door won't lock or the gasket leaks. Repair: AED 180–350." },
      { title: 'Motor / Bearing Wear', desc: 'Grinding and vibration on spin. Repair: AED 350–650.' },
      { title: 'Control Board Fault', desc: "Error codes or a cycle that won't start. Repair: AED 300–550." },
    ],
    'AEG premium-electronics expertise with genuine parts for these German-engineered machines.',
    '350+',
    'AEG Washing Machine Repair Dubai | ProSense Experts',
    'Same-day AEG washing machine repair in Dubai. ÖKOMix & ProSense specialists, genuine parts, 12-month warranty.',
  ),
  make(
    'Sharp', 'sharp.eu', 'Asian',
    'Plasmacluster · Inverter · Bubble Drum',
    "Sharp washing machines bring Japanese reliability and Plasmacluster hygiene to Dubai homes. We repair Sharp's automatic and inverter ranges, resolving motor, drainage and control faults with genuine parts and same-day service.",
    'ES-series front-load, top-load & inverter models',
    [
      { title: 'Inverter Motor Fault', desc: 'No spin or mid-cycle stops from the inverter drive. Repair: AED 300–650.' },
      { title: 'Drain Pump Blockage', desc: 'Standing water with a drainage error. Repair: AED 200–400.' },
      { title: 'Door Lock Fault', desc: "The door won't lock or release. Repair: AED 180–350." },
      { title: 'Water Inlet Valve Fault', desc: 'Slow or no filling. Repair: AED 150–300.' },
      { title: 'Bearing & Vibration', desc: 'Noise and shaking on spin. Repair: AED 350–600.' },
    ],
    'Sharp automatic and inverter expertise with genuine parts for reliable, same-day repairs.',
    '400+',
    'Sharp Washing Machine Repair Dubai | Plasmacluster Fix',
    'Same-day Sharp washing machine repair in Dubai. Plasmacluster & inverter experts, genuine parts, 12-month warranty.',
  ),
  make(
    'Gorenje', 'gorenje.com', 'Premium European',
    'WaveActive · IonTech · SensoCare',
    "Gorenje adds Slovenian design and WaveActive drums to the Dubai market, with IonTech freshness and SensoCare programs. We repair the full Gorenje front-load range, resolving electronic, heating and drainage faults with genuine European parts.",
    'WaveActive & SensoCare front-load series',
    [
      { title: 'Heating Element Scaling', desc: "Cool washes and slower cycles from Dubai's hard water. Repair: AED 150–300." },
      { title: 'Drain Pump Fault', desc: 'Standing water and a drainage error. Repair: AED 200–400.' },
      { title: 'Door Lock / Seal Fault', desc: "The door won't lock or the gasket leaks. Repair: AED 180–350." },
      { title: 'Control Board Fault', desc: "Error codes or a cycle that won't start. Repair: AED 300–550." },
      { title: 'Bearing Wear', desc: 'Grinding and vibration on spin. Repair: AED 350–600.' },
    ],
    'Genuine European parts and Gorenje WaveActive expertise for Dubai homes.',
    '300+',
    'Gorenje Washing Machine Repair Dubai | WaveActive Experts',
    'Same-day Gorenje washing machine repair in Dubai. WaveActive & SensoCare experts, genuine parts, warranty.',
  ),
  make(
    'Candy', 'candy-home.com', 'Global Major',
    'Rapidó · Smart Touch · Wi-Fi + BLE',
    "Candy washing machines offer Italian design, Rapidó fast washing and Smart Touch Wi-Fi connectivity at a competitive price. We repair both the connected and conventional Candy ranges across Dubai, fixing app, motor and drainage faults with genuine parts.",
    'Rapidó & Smart Touch front-load series',
    [
      { title: 'Motor / Belt Fault', desc: 'No spin or a slipping belt leaving clothes soaked. Repair: AED 300–650.' },
      { title: 'Smart Touch / Board Fault', desc: "Connectivity drops or an unresponsive panel. Repair: AED 250–500." },
      { title: 'Drain Pump Blockage', desc: 'Water remains in the drum after the cycle. Repair: AED 200–400.' },
      { title: 'Door Lock Fault', desc: "The door won't open or lock. Repair: AED 180–350." },
      { title: 'Bearing & Drum Wear', desc: 'Grinding and vibration on older machines. Repair: AED 350–600.' },
    ],
    'Experience with both Smart Touch Wi-Fi and conventional Candy machines, with genuine UAE parts.',
    '400+',
    'Candy Washing Machine Repair Dubai | Smart Touch Fix',
    'Same-day Candy washing machine repair in Dubai. Rapidó & Smart Touch specialists, genuine parts, 12-month warranty.',
  ),
  make(
    'Zanussi', 'zanussi.com', 'Premium European',
    'Jet System · AquaFall · FuzzyLogic',
    "Zanussi brings Italian engineering and Jet System washing to Dubai homes at an accessible price point. Our technicians repair the full Zanussi front-load range, resolving heating, drainage and electronic faults with genuine European parts.",
    'Jet System & AquaFall front-load series',
    [
      { title: 'Heating Element Limescale', desc: "Cool washes and higher energy use from hard water. Repair: AED 150–300." },
      { title: 'Drain Pump Fault', desc: 'Standing water and a drainage error. Repair: AED 200–400.' },
      { title: 'Door Lock / Seal Fault', desc: "The door won't lock or the gasket leaks. Repair: AED 180–350." },
      { title: 'Control Board Fault', desc: "Error codes or a cycle that won't start. Repair: AED 300–550." },
      { title: 'Bearing Wear', desc: 'Grinding and vibration on spin. Repair: AED 350–600.' },
    ],
    'Genuine European parts and Zanussi Jet System expertise for Dubai laundry rooms.',
    '300+',
    'Zanussi Washing Machine Repair Dubai | Jet System Experts',
    'Same-day Zanussi washing machine repair in Dubai. Jet System & AquaFall experts, genuine parts, warranty.',
  ),
  make(
    'Indesit', 'indesit.com', 'Global Major',
    'Push & Wash · Innex · Water Balance',
    "Indesit machines offer straightforward, dependable washing with Push & Wash one-touch programs, popular in Dubai apartments. We repair the full Indesit front-load and top-load range, fixing motor, pump and control faults with genuine parts.",
    'Innex & Push & Wash front-load and top-load series',
    [
      { title: 'Motor / Belt Fault', desc: 'No spin or a slipping belt leaving clothes soaked. Repair: AED 300–650.' },
      { title: 'Drain Pump Blockage', desc: 'Water remains in the drum after the cycle. Repair: AED 200–400.' },
      { title: 'Door Lock Fault', desc: "The door won't open or lock. Repair: AED 180–350." },
      { title: 'Heating Element Scaling', desc: 'Cool washes from hard-water limescale. Repair: AED 150–300.' },
      { title: 'Control Board Fault', desc: "Error codes or a cycle that won't start. Repair: AED 300–550." },
    ],
    'Dependable Indesit repairs with genuine parts for the machines common in Dubai apartments.',
    '350+',
    'Indesit Washing Machine Repair Dubai | Push & Wash Fix',
    'Same-day Indesit washing machine repair in Dubai. Innex & Push & Wash experts, genuine parts, 12-month warranty.',
  ),
  make(
    'Akai', 'akai.com', 'Regional / Value',
    'Automatic · Semi-Automatic · Twin-Tub',
    "Akai washing machines are a familiar value choice in the UAE, offering automatic, semi-automatic and twin-tub options for budget-conscious homes. We repair the full Akai range across Dubai, keeping affordable motors, belts, timers and pumps in stock for fast service.",
    'Automatic, semi-automatic & twin-tub models',
    [
      { title: 'Pulsator / Belt Fault', desc: 'Weak or no wash action. Repair: AED 140–320.' },
      { title: 'Spin Motor Fault', desc: 'The spinner stalls, leaving clothes soaked. Repair: AED 180–380.' },
      { title: 'Drain Valve / Pump Fault', desc: "Water won't drain from the tub. Repair: AED 120–300." },
      { title: 'Timer / Control Fault', desc: "The cycle won't advance. Repair: AED 130–300." },
      { title: 'Water Leak from Tub', desc: 'Leaks from a worn seal or cracked valve. Repair: AED 100–280.' },
    ],
    'Fast, affordable Akai repairs for budget homes across Dubai, with parts in stock.',
    '400+',
    'Akai Washing Machine Repair Dubai | Same-Day Service',
    'Same-day Akai washing machine repair in Dubai. Automatic & twin-tub experts, genuine parts, 12-month warranty.',
  ),
  make(
    'Geepas', 'geepas.com', 'Regional / Value',
    'Compact Auto · Semi-Automatic · Twin-Tub',
    "Geepas is a popular UAE value brand offering compact automatic, semi-automatic and twin-tub washing machines for apartments and smaller homes. We keep strong Geepas parts availability and repair the full range across Dubai with fast turnaround.",
    'Compact automatic, semi-automatic & twin-tub models',
    [
      { title: 'Pulsator Gear Wear', desc: 'Reduced wash action with clothes not agitating fully. Repair: AED 130–270.' },
      { title: 'Drain Hose / Outlet Blockage', desc: 'Slow or no drainage from the tub. Repair: AED 90–200.' },
      { title: 'Wash Motor Coupling Fault', desc: "The motor runs but doesn't drive the pulsator. Repair: AED 140–300." },
      { title: 'Control Knob Damage', desc: "The timer or wash-level knob breaks or won't turn. Repair: AED 100–220." },
      { title: 'Water Leak from Tub', desc: 'Leaks from a worn seal or cracked valve. Repair: AED 100–260.' },
    ],
    'Strong Geepas parts availability for the compact machines common in Dubai apartments.',
    '450+',
    'Geepas Washing Machine Repair Dubai | Same-Day Fix',
    'Same-day Geepas washing machine repair in Dubai. Compact auto & twin-tub experts, genuine parts, warranty.',
  ),
  make(
    'Black+Decker', 'blackanddecker.com', 'Regional / Value',
    'Twin-Tub · Semi-Automatic',
    "Black+Decker washing machines bring the trusted tool brand's value to UAE laundry rooms, mainly through twin-tub and semi-automatic models. We repair the full Black+Decker range across Dubai, keeping belts, motors, timers and drain valves in stock for affordable fixes.",
    'Twin-tub & semi-automatic models',
    [
      { title: 'Pulsator / Belt Fault', desc: 'Weak or no wash action on the wash side. Repair: AED 140–320.' },
      { title: 'Spin Motor / Bearing Fault', desc: 'The spinner grinds or stalls. Repair: AED 180–380.' },
      { title: 'Drain Valve Fault', desc: "Water won't drain from the tub. Repair: AED 120–280." },
      { title: 'Timer / Control Fault', desc: "The cycle won't advance or the buzzer is silent. Repair: AED 130–300." },
      { title: 'Water Leak from Tub', desc: 'Leaks from a worn seal or cracked valve. Repair: AED 100–280.' },
    ],
    'Affordable Black+Decker twin-tub repairs with parts in stock for fast Dubai service.',
    '300+',
    'Black+Decker Washing Machine Repair Dubai | Twin-Tub Fix',
    'Same-day Black+Decker washing machine repair in Dubai. Twin-tub & semi-auto experts, genuine parts, warranty.',
  ),
  make(
    'Generaltec', 'generaltec.net', 'Regional / Value',
    'Automatic · Twin-Tub · Semi-Automatic',
    "Generaltec is a UAE electronics brand offering affordable automatic and twin-tub washing machines for everyday homes. Our technicians repair the full Generaltec range across Dubai, with belts, motors, timers and pumps in stock for quick, budget-friendly service.",
    'Automatic front-load, twin-tub & semi-automatic models',
    [
      { title: 'Pulsator / Belt Fault', desc: 'Weak or no wash action. Repair: AED 140–320.' },
      { title: 'Spin Motor Fault', desc: 'The spinner stalls, leaving clothes soaked. Repair: AED 180–380.' },
      { title: 'Drain Valve / Pump Fault', desc: "Water won't drain from the tub. Repair: AED 120–300." },
      { title: 'Timer / Control Fault', desc: "The cycle won't advance. Repair: AED 130–300." },
      { title: 'Water Leak from Tub', desc: 'Leaks from a worn seal or cracked valve. Repair: AED 100–280.' },
    ],
    'Quick, budget-friendly Generaltec repairs with parts in stock across Dubai.',
    '300+',
    'Generaltec Washing Machine Repair Dubai | Same-Day Fix',
    'Same-day Generaltec washing machine repair in Dubai. Automatic & twin-tub experts, genuine parts, warranty.',
  ),
  make(
    'Terim', 'terim.ae', 'Regional / Value',
    'Automatic · Twin-Tub · UAE Brand',
    "Terim is a UAE-focused brand offering practical automatic and twin-tub washing machines built for the local market. We repair the full Terim range across Dubai villas, apartments and staff accommodation, keeping affordable parts in stock for fast turnaround.",
    'Automatic front-load & twin-tub models',
    [
      { title: 'Pulsator / Belt Fault', desc: 'Weak or no wash action. Repair: AED 140–320.' },
      { title: 'Spin Motor / Bearing Fault', desc: 'The spinner grinds or stalls. Repair: AED 180–380.' },
      { title: 'Drain Valve / Pump Fault', desc: "Water won't drain from the tub. Repair: AED 120–300." },
      { title: 'Timer / Control Fault', desc: "The cycle won't advance. Repair: AED 130–300." },
      { title: 'Water Leak from Tub', desc: 'Leaks from a worn seal or cracked valve. Repair: AED 100–280.' },
    ],
    'Local Terim expertise with affordable parts for fast repairs across Dubai.',
    '300+',
    'Terim Washing Machine Repair Dubai | Same-Day Service',
    'Same-day Terim washing machine repair in Dubai. Automatic & twin-tub experts, genuine parts, 12-month warranty.',
  ),
  make(
    'Olsenmark', 'olsenmark.com', 'Regional / Value',
    'Twin-Tub · Semi-Automatic',
    "Olsenmark is a UAE value brand known for affordable twin-tub and semi-automatic washing machines suited to apartments and labour accommodation. We repair the full Olsenmark range across Dubai, keeping belts, motors, timers and drain valves in stock.",
    'Twin-tub & semi-automatic models',
    [
      { title: 'Pulsator / Belt Fault', desc: 'Weak or no wash action on the wash side. Repair: AED 140–320.' },
      { title: 'Spin Motor Fault', desc: 'The spinner grinds or stalls. Repair: AED 180–380.' },
      { title: 'Drain Valve Fault', desc: "Water won't drain from the tub. Repair: AED 120–280." },
      { title: 'Timer / Control Fault', desc: "The cycle won't advance or the buzzer is silent. Repair: AED 130–300." },
      { title: 'Water Leak from Tub', desc: 'Leaks from a worn seal or cracked valve. Repair: AED 100–280.' },
    ],
    'Affordable Olsenmark twin-tub repairs with parts in stock for fast Dubai service.',
    '300+',
    'Olsenmark Washing Machine Repair Dubai | Twin-Tub Fix',
    'Same-day Olsenmark washing machine repair in Dubai. Twin-tub & semi-auto experts, genuine parts, warranty.',
  ),
  make(
    'Westpoint', 'westpoint.ae', 'Regional / Value',
    'Automatic · Twin-Tub · Semi-Automatic',
    "Westpoint is a long-established value brand in the UAE, offering automatic, semi-automatic and twin-tub washing machines for everyday homes. Our technicians repair the full Westpoint range across Dubai with affordable parts and fast turnaround.",
    'Automatic front-load, twin-tub & semi-automatic models',
    [
      { title: 'Pulsator / Belt Fault', desc: 'Weak or no wash action. Repair: AED 140–320.' },
      { title: 'Spin Motor / Bearing Fault', desc: 'The spinner grinds or stalls. Repair: AED 180–380.' },
      { title: 'Drain Valve / Pump Fault', desc: "Water won't drain from the tub. Repair: AED 120–300." },
      { title: 'Timer / Control Fault', desc: "The cycle won't advance. Repair: AED 130–300." },
      { title: 'Water Leak from Tub', desc: 'Leaks from a worn seal or cracked valve. Repair: AED 100–280.' },
    ],
    'Long-standing Westpoint experience with affordable parts for everyday Dubai homes.',
    '400+',
    'Westpoint Washing Machine Repair Dubai | Same-Day Fix',
    'Same-day Westpoint washing machine repair in Dubai. Automatic & twin-tub experts, genuine parts, warranty.',
  ),
  make(
    'National', 'national.com.pk', 'Regional / Value',
    'Twin-Tub · Semi-Automatic · Auto',
    "National-branded washing machines remain popular in UAE homes and staff accommodation for their simple, rugged twin-tub and semi-automatic designs. We repair the full range across Dubai, keeping belts, motors, timers and drain valves in stock for fast, low-cost fixes.",
    'Twin-tub, semi-automatic & automatic models',
    [
      { title: 'Pulsator / Belt Fault', desc: 'Weak or no wash action on the wash side. Repair: AED 140–320.' },
      { title: 'Spin Motor / Bearing Fault', desc: 'The spinner grinds or stalls. Repair: AED 180–380.' },
      { title: 'Drain Valve Fault', desc: "Water won't drain from the tub. Repair: AED 120–280." },
      { title: 'Timer / Control Fault', desc: "The cycle won't advance or the buzzer is silent. Repair: AED 130–300." },
      { title: 'Water Leak from Tub', desc: 'Leaks from a worn seal or cracked valve. Repair: AED 100–280.' },
    ],
    'Rugged, low-cost National repairs for high-usage homes and accommodation across Dubai.',
    '450+',
    'National Washing Machine Repair Dubai | Twin-Tub Experts',
    'Same-day National washing machine repair in Dubai. Twin-tub & semi-automatic experts, genuine parts, warranty.',
  ),
  make(
    'Mika', 'mika.co.ke', 'Regional / Value',
    'Twin-Tub · Semi-Automatic',
    "Mika offers affordable twin-tub and semi-automatic washing machines that appear in UAE homes and shared accommodation. We repair the Mika range across Dubai, keeping affordable belts, motors, timers and pumps in stock for quick service.",
    'Twin-tub & semi-automatic models',
    [
      { title: 'Pulsator / Belt Fault', desc: 'Weak or no wash action. Repair: AED 140–320.' },
      { title: 'Spin Motor Fault', desc: 'The spinner grinds or stalls. Repair: AED 180–380.' },
      { title: 'Drain Valve Fault', desc: "Water won't drain from the tub. Repair: AED 120–280." },
      { title: 'Timer / Control Fault', desc: "The cycle won't advance. Repair: AED 130–300." },
      { title: 'Water Leak from Tub', desc: 'Leaks from a worn seal or cracked valve. Repair: AED 100–280.' },
    ],
    'Quick, affordable Mika repairs with parts in stock across Dubai.',
    '250+',
    'Mika Washing Machine Repair Dubai | Twin-Tub Service',
    'Same-day Mika washing machine repair in Dubai. Twin-tub & semi-automatic experts, genuine parts, warranty.',
  ),
  make(
    'Mitsubishi Electric', 'mitsubishielectric.com', 'Asian',
    'Japanese Engineering · Inverter · Auto',
    "Mitsubishi Electric washing machines are valued for precise Japanese engineering and quiet inverter operation. Our Dubai technicians repair the range with genuine parts, resolving motor, drainage and electronic faults on both current and older models.",
    'Automatic front-load, top-load & inverter models',
    [
      { title: 'Inverter Motor Fault', desc: 'No spin or mid-cycle stops from the inverter drive. Repair: AED 350–650.' },
      { title: 'Water Level Sensor Fault', desc: 'Over- or under-filling affecting wash quality. Repair: AED 150–300.' },
      { title: 'Drainage Blockage', desc: 'Water remains in the drum from a blocked pump. Repair: AED 200–400.' },
      { title: 'Control Board Fault', desc: 'The machine freezes or halts mid-cycle. Repair: AED 300–550.' },
      { title: 'Bearing & Drum Wear', desc: 'Grinding and vibration on spin. Repair: AED 350–600.' },
    ],
    'Precise Mitsubishi Electric repairs with genuine parts for quiet, long-life Japanese machines.',
    '300+',
    'Mitsubishi Electric Washing Machine Repair Dubai',
    'Same-day Mitsubishi Electric washing machine repair in Dubai. Inverter experts, genuine parts, 12-month warranty.',
  ),
  make(
    'Fisher & Paykel', 'fisherpaykel.com', 'Premium European',
    'SmartDrive · AktiveIntelligence · ECS',
    "Fisher & Paykel brings New Zealand engineering and the direct-drive SmartDrive motor to premium Dubai laundry rooms. Our technicians handle its AktiveIntelligence sensing and genuine SmartDrive components to keep these long-life machines performing.",
    'SmartDrive top-load & front-load series',
    [
      { title: 'SmartDrive Motor Fault', desc: 'No spin or erratic operation from the direct-drive motor. Repair: AED 400–700.' },
      { title: 'AktiveIntelligence Sensor Fault', desc: 'Wrong water levels or cycle behaviour. Repair: AED 200–400.' },
      { title: 'Drain Pump Fault', desc: 'Standing water and a drainage error. Repair: AED 200–400.' },
      { title: 'Lid Lock / Door Fault', desc: "The lid or door won't lock or release. Repair: AED 180–380." },
      { title: 'Control Board Fault', desc: "Error codes or a cycle that won't start. Repair: AED 300–550." },
    ],
    'Careful Fisher & Paykel handling with genuine SmartDrive parts for premium machines.',
    '250+',
    'Fisher & Paykel Washing Machine Repair Dubai | SmartDrive',
    'Same-day Fisher & Paykel washing machine repair in Dubai. SmartDrive specialists, genuine parts, warranty.',
  ),
  make(
    'Teka', 'teka.com', 'Premium European',
    'ProTouch · Inverter · SteamCare',
    "Teka brings Spanish and German engineering to Dubai homes with ProTouch controls and inverter washing. We repair the full Teka front-load range, resolving heating, drainage and electronic faults with genuine European parts.",
    'ProTouch & inverter front-load series',
    [
      { title: 'Inverter Motor Fault', desc: 'No spin or mid-cycle stops. Repair: AED 300–650.' },
      { title: 'Heating Element Scaling', desc: "Cool washes from Dubai's hard water. Repair: AED 150–300." },
      { title: 'Drain Pump Fault', desc: 'Standing water and a drainage error. Repair: AED 200–400.' },
      { title: 'Door Lock / Seal Fault', desc: "The door won't lock or the gasket leaks. Repair: AED 180–350." },
      { title: 'Control Board Fault', desc: "Error codes or a cycle that won't start. Repair: AED 300–550." },
    ],
    'Genuine European parts and Teka inverter expertise for Dubai laundry rooms.',
    '250+',
    'Teka Washing Machine Repair Dubai | Inverter Experts',
    'Same-day Teka washing machine repair in Dubai. ProTouch & inverter experts, genuine parts, 12-month warranty.',
  ),
  make(
    'BPL', 'bpl.in', 'Regional / Value',
    'Automatic · Semi-Automatic',
    "BPL washing machines offer dependable automatic and semi-automatic washing at a value price, and appear in many UAE homes. Our technicians repair the BPL range across Dubai with affordable parts and fast turnaround.",
    'Automatic front-load & semi-automatic models',
    [
      { title: 'Pulsator / Belt Fault', desc: 'Weak or no wash action. Repair: AED 140–320.' },
      { title: 'Spin Motor Fault', desc: 'The spinner grinds or stalls. Repair: AED 180–380.' },
      { title: 'Drain Valve / Pump Fault', desc: "Water won't drain from the tub. Repair: AED 120–300." },
      { title: 'Timer / Control Fault', desc: "The cycle won't advance. Repair: AED 130–300." },
      { title: 'Water Leak from Tub', desc: 'Leaks from a worn seal or cracked valve. Repair: AED 100–280.' },
    ],
    'Dependable, affordable BPL repairs with parts in stock across Dubai.',
    '250+',
    'BPL Washing Machine Repair Dubai | Same-Day Service',
    'Same-day BPL washing machine repair in Dubai. Automatic & semi-automatic experts, genuine parts, warranty.',
  ),
];

export const BRAND_BY_SLUG: Record<string, BrandEntry> = Object.fromEntries(
  BRANDS.map((b) => [b.slug, b]),
);

// Map used by nav/grid: brand name -> route path.
export const BRAND_HREF: Record<string, string> = Object.fromEntries(
  BRANDS.map((b) => [b.name, `/${b.slug}`]),
);
